import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
export const CARD_WIDTH = width * 0.92;
export const CARD_HEIGHT = CARD_WIDTH * 1.45;

export const characterCardStyles = StyleSheet.create({
  cardShadow: {
    borderRadius: 28,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 16,
    // Sombra externa adicional
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
  },
  animatedCard: {
    borderRadius: 28,
    backgroundColor: '#1a1a2e',
    overflow: 'hidden',
  },
  cardContainer: {
    borderRadius: 28,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    alignItems: 'center',
    position: 'relative',
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  //  background: 'linear-gradient(180deg, transparent 0%, transparent 40%, rgba(0,0,0,0.2) 70%, rgba(0,0,0,0.8) 100%)',
    zIndex: 1,
  },
  nameBottomContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.85)',
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    zIndex: 3,
    borderTopWidth: 2,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  nameBottomText: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 1.2,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
    textTransform: 'uppercase',
  },
  attributesContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    paddingHorizontal: 10,
    paddingTop: 4,
    paddingBottom: 8,
    zIndex: 2,
    borderTopWidth: 1,
    borderTopColor: 'rgba(59, 130, 246, 0.18)',
  },
  attributeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(59, 130, 246, 0.10)',
    marginBottom: 1,
  },
  lastAttributeRow: {
    borderBottomWidth: 0,
    marginBottom: 0,
  },
  attrLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  attrIcon: {
    fontSize: 15,
    marginRight: 7,
    width: 18,
    textAlign: 'center',
  },
  attrLabel: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.3,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  attrValueContainer: {
    backgroundColor: 'rgba(251, 191, 36, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.18)',
    minWidth: 32,
    alignItems: 'center',
  },
  attrValue: {
    color: '#fbbf24',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    textShadowColor: '#92400e',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  groupIndicator: {
    position: 'absolute',
    top: 20,
    right: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    zIndex: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 8,
  },
  groupText: {
    color: '#000',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    textShadowColor: 'rgba(255,255,255,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  nameFooterContainer: {
    width: '100%',
    backgroundColor: '#111',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginTop: 0,
  },
  nameFooterText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 1.2,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    textTransform: 'uppercase',
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    backgroundColor: 'rgba(15,23,42,0.18)',
    paddingHorizontal: 0,
    paddingVertical: 0,
    zIndex: 1,
    justifyContent: 'center',
  },
  attributesContent: {
    zIndex: 2,
    position: 'relative',
    flexDirection: 'column',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  innerCardContainer: {
    width: CARD_WIDTH - 12,
    height: CARD_HEIGHT,
    alignSelf: 'center',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#1a1a2e',
  },
  innerCardImage: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
  },
  outerCardContainer: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    borderRadius: 28,
    padding: 0,
  },
});