import { StyleSheet } from "react-native";

export const miniCharacterCardStyles = StyleSheet.create({
  cardShadow: {
    borderRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
    elevation: 8,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 4,
    borderWidth: 4,
    borderColor: "#fff",
    backgroundColor: "transparent",
  },
  cardContainer: {
    borderRadius: 14,
    overflow: "hidden",
    justifyContent: "flex-end",
    alignItems: "center",
    position: "relative",
    backgroundColor: "#111",
  },
  cardImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  nameBottomContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.68)",
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  nameBottomText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
    textTransform: "uppercase",
  },

  highlightOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    alignItems: "center",
  },
  highlightAttributeName: {
    color: "#facc15",
    fontSize: 20,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  highlightAttributeValue: {
    color: "#fff",
    fontSize: 48,
    fontWeight: "900",
    textShadowColor: "#facc15",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
});
